[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aigise"
version = "0.1.0"
description = "AIgiSE"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas==2.2.3",
    "neomodel==5.4.3",
    "docker==7.1.0",
    "python-dotenv==1.1.0",
    "tree-sitter-languages==1.10.2",
    "loguru==0.7.3",
    "pyyaml==6.0.2",
    "requests==2.32.4",
    "google-adk==1.5.0",
    "litellm>=1.74.7",
    "msgspec>=0.19.0",
    "tenacity>=9.1.2",
]

[tool.uv]
override-dependencies = []
no-build-isolation-package = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-async>=0.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/aigise"]

[tool.hatch.build.targets.sdist]
include = ["/src", "/pyproject.toml", "/README.md"]
