[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aigise"
version = "0.1.0"
description = "AIgiSE"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire",
    "litellm",
    "tenacity",
    "loguru",
    "docker",
    "jsonpickle",
    "neomodel",
    "tree-sitter-languages>=1.10.2",
    "boto3>=1.40.21",
    "transformers>=4.56.0",
    "datasets>=4.0.0",
    "google-adk>=1.13.0",
    "cybergym[dev,server]",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ipython",
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[tool.uv]
override-dependencies = []
no-build-isolation-package = []

[tool.uv.sources]
cybergym = { path = "third_party/cybergym", editable = false }

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
extend-exclude = ["third_party/**"]

[tool.ruff.lint]
select = [
    "I", # isort
    "F", # pyflakes
]
ignore = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"
