[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "algise"
version = "0.1.0"
description = "AIgiSE"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire",
    "litellm",
    "tenacity",
    "loguru",
    "p-tqdm",
    "natsort",
    "boto3>=1.40.21",
    "transformers>=4.56.0",
    "datasets>=4.0.0",
]

[project.optional-dependencies]

[tool.uv]
override-dependencies = [
]
no-build-isolation-package = []

[dependency-groups]
dev = [
    "black",
    "debugpy",
    "ipython",
    "pre-commit",
]
