MAX_TOOL_RESPONSE_LENGTH = 15000
MAX_HISTORY_SUMMARY_LENGTH = 240000
[llm]
model_name = "gemini-3-flash-preview"
temperature = 0.7

[build]
run_command = "echo 'Please check the problem statement and the repository for how to reproduce the issue.'."
compile_command = "echo 'No compilation needed'"

[llm.model_configs.summarize]
model_name = "inherit"
temperature = 1

[history]
max_tool_response_length = "${MAX_TOOL_RESPONSE_LENGTH}"
enable_quota_countdown = true
max_history_summary_length = "${MAX_HISTORY_SUMMARY_LENGTH}"

[history.events_compaction]
max_history_summary_length = "${MAX_HISTORY_SUMMARY_LENGTH}"
compaction_percent = 50

[subagent]

[sandbox]
backend = "native"

[sandbox.sandboxes.main]
image = "${DEFAULT_IMAGE}"
working_dir = "/workspace"
command = ""
timeout = 300

[plugins]
enabled = [
    "build_verifier_plugin",
    "doom_loop_detector_plugin",
    "read_before_edit_plugin",
    "history_summarizer_plugin",
    "tool_response_summarizer_plugin",
    "careful_edit",
    "test_output_review",
]
