[llm]
model_name = "gemini-2.0-flash-exp"
temperature = 0.7

[build]
run_command = "echo 'Please check the problem statement and the repository for how to reproduce the issue.'"
compile_command = "echo 'No compilation needed'"

[sandbox]
backend = "native"

[sandbox.sandboxes.main]
image = "${DEFAULT_IMAGE}_main"
working_dir = "/workspace"
command = "-c 'while true; do sleep 3600; done'"
project_relative_dockerfile_path = "src/aigise/templates/dockerfiles/main/Dockerfile"
timeout = 300
[sandbox.sandboxes.main.build_args]
BASE_IMAGE = "${DEFAULT_IMAGE}"
