services:
  callgraph-neo4j:
    image: neo4j:5.26.12-enterprise
    network_mode: bridge
    restart: always
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_AUTH: neo4j/callgraphn4j!
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    volumes:
      - type: volume
        source: shared_volume
        target: /data
        volume:
          subpath: neo4j_db/data
      - type: volume
        source: shared_volume
        target: /logs
        volume:
          subpath: neo4j_db/logs
      - type: volume
        source: shared_volume
        target: /plugins
        volume:
          subpath: neo4j_db/plugins
      - type: volume
        source: shared_volume
        target: /var/lib/neo4j/import
        volume:
          subpath: neo4j_db/import

volumes:
  shared_volume:
    name: ${SHARED_VOLUME_NAME}
    external: true
